### ISSUE TITLE
Cancel does not work in bulk-convert

### ISSUE THREAD

**Issue by SaraSmiseth** [Ajatt-Tools/PasteImagesAsWebP#11]
I opened the bulk-convert menu by Edit > Bulk-convert to WebP in the card browser. The settings window was opened, but I wanted to select more cards, so I clicked cancel. It did not cancel and converted my images.

**Comment by tatsumoto-ren** [comment]
Strange.

The cancel button does seem to work fine for me, but it is designed so that when you cancel it simply stops processing the images, it doesn't undo the changes that it already did. If you want to undo a conversion task, press "Edit" > "Undo".

**Comment by tatsumoto-ren** [comment]
Now I understand what it's about. I'll test it to see if I can reproduce this.
