### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by AH349** [Ajatt-Tools/PasteImagesAsWebP#14]
Can the "Bulk-convert to WebP" feature be applied to a specific field in a note? 
I didn't find an option for that. It'd be a great feature for notes that have multiple fields but you wish to run the addon just on some of them.

THANK YOU!

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/PasteImagesAsWebP/blob/main/.github/ISSUE_TEMPLATE/issue.md)

There's no option for that but it can be added.

**Comment by AH349** [comment]
It'd be amazing if it can be included in a future update, thanks!!

**Comment by tatsumoto-ren** [comment]
Should work now. Please test.

**Comment by AH349** [comment]
I'm stocked, that's perfect! 

Thank you!

**Comment by AH349** [comment]
H!
the reason I like the ability to select images to convert has to do with
the decrease in resolution of images after conversion. Many images I have
are of algorithms and schemes with many details that get too blurry after
conversion. Others are more general pictures that are absolutely perfect
for this conversion.

I understand if it's too much by this point, and I really appreciate it,
this is a TOP addon as is!

Thanks a lot!
