### ISSUE TITLE
Trying to git clone the addon ends up in an error

### ISSUE THREAD

**Issue by kuator** [Ajatt-Tools/PasteImagesAsWebP#15]
Running `git clone 'https://github.com/Ajatt-Tools/PasteImagesAsWebP.git' ~/.local/share/Anki2/addons21/PasteImagesAsWebP` and then trying to open Anking ends up in an error at the startup.

![Screenshot from 2022-05-12 17-18-30](https://user-images.githubusercontent.com/25168308/168063170-58db2d5b-d13b-491a-ae8d-daae80fb3575.png)

**Comment by kuator** [comment]
Anki 2.1.49

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/PasteImagesAsWebP/blob/main/.github/ISSUE_TEMPLATE/issue.md)

**Comment by tatsumoto-ren** [comment]
The error on the screenshot says that you don't have `cwebp` installed. Try installing [libwebp](https://archlinux.org/packages/extra/x86_64/libwebp/).

**Comment by kuator** [comment]
> The error on the screenshot suggests that you don't have `cwebp` installed. Try installing [libwebp](https://archlinux.org/packages/extra/x86_64/libwebp/).

![Screenshot from 2022-05-12 17-44-37](https://user-images.githubusercontent.com/25168308/168067480-fab25bbc-a680-4754-8cd6-d67ff57da2a0.png)
I installed it though

**Comment by tatsumoto-ren** [comment]
Still not installed? Does `which cwebp` return the path?

**Comment by kuator** [comment]
Unable to locate package cwebp

**Comment by tatsumoto-ren** [comment]
Have you tried installing the addon [from ankiweb](https://ankiweb.net/shared/info/1151815987)?

**Comment by tatsumoto-ren** [comment]
> cannot import menu_root_entry

sub-modules aren't initialized.

**Comment by kuator** [comment]
> Have you tried installing the addon [from ankiweb](https://ankiweb.net/shared/info/1151815987)?

It most probably is going to work. I just wanted to automate process of installing anki addons. That's the reason I went with git

**Comment by kuator** [comment]
> > cannot import menu_root_entry
> 
> sub-modules aren't initialized.

Thank you, would it be possible to put a mention in the readme, so in the future people wouldn't stumble like me?

**Comment by kuator** [comment]
> > cannot import menu_root_entry
> 
> sub-modules aren't initialized.

Thank you!

**Comment by tatsumoto-ren** [comment]
Usually the only time you'd want to install an anki add-on directly from github instead from ankiweb is when you want to participate in the development.

I'll change the readme to include additional info.
