### ISSUE TITLE
Suggestion : Add recommandation in Github and ankiweb

### ISSUE THREAD

**Issue by sangorys** [Ajatt-Tools/PasteImagesAsWebP#18]
Hello,

I am so sorry to write an issue for this but I am not skilled enough to find another way to contact the great developer(s) of this plugin !!!

Would you please advice what are the best configuration for webp : size and quality compression ? Would you write these recommendations in GitHub and in AnkiWeb ?

I appreciate you help !!!

**Comment by tatsumoto-ren** [comment]
Hello

Our contacts are listed here: https://tatsumoto.neocities.org/blog/join-our-community.html

> what are the best configuration for webp : size and quality compression

See my settings below:

![screenshot-2022-07-23-21-31-06](https://user-images.githubusercontent.com/69171671/180623477-27879e74-96b4-4a31-a921-7afc978e7ee6.png)

Although I must point out that everybody has their own preferences.
