### ISSUE TITLE
Inputting any number less than 5 in the settings menu inputs a 0 instead

### ISSUE THREAD

**Issue by Syntribos** [Ajatt-Tools/PasteImagesAsWebP#2]
When changing the settings for width/height/quality, the first number entered will always be a 0 unless it's >=5. For instance, if you type "250" for height, it will be interpreted as 050 and be set to 50. To enter 250, You would have to type 50 first and then prepend a 2.

OS: Windows 10
Anki version: 2.1.22
Python 3.8.0

**Comment by tatsumoto-ren** [comment]
Thank you for the issue. Indeed, I could reproduce this bug. I'll remove the code that recalculates the typed values.
