### ISSUE TITLE
Adjust maximum image dimensions

### ISSUE THREAD

**Issue by SirChurchill9999** [Ajatt-Tools/PasteImagesAsWebP#22]
The add-on named Image Resizer allows the user to scale the image to the maximum dimension upon pasting (width or height). For instance, I have it set to 1200x1500, so the image will scale to the maximum of either of those, whichever comes first. You can also disable upscaling.

Can you implement this feature? This add-on is currently capped at 800x600, which is quite small, especially on desktops.

**Comment by tatsumoto-ren** [comment]
The maximum boundaries can be changed in the config file.

**Comment by SirChurchill9999** [comment]
> The maximum boundaries can be changed in the config file.

Thanks for the reply - figured that out! Appreciate everything you do.
