### ISSUE TITLE
Add-on fails to load on Manjaro KDE (error)

### ISSUE THREAD

**Issue by Exponent4806** [Ajatt-Tools/PasteImagesAsWebP#24]
Error
One of the installed extensions could not be loaded. If the problem persists, please deactivate or uninstall the extensions via the menu item Extras → Extensions.

When loading  '⁨Paste Images As WebP⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/m/.local/share/Anki2/addons21/1151815987/__init__.py", line 19, in <module>
    from . import bulkconvert, events, menus, media_rename
  File "/home/m/.local/share/Anki2/addons21/1151815987/bulkconvert.py", line 30, in <module>
    from .common import *
  File "/home/m/.local/share/Anki2/addons21/1151815987/common.py", line 26, in <module>
    from .config import config
  File "/home/m/.local/share/Anki2/addons21/1151815987/config.py", line 24, in <module>
    from .ajt_common.addon_config import AddonConfigManager
ModuleNotFoundError: No module named '1151815987.ajt_common'
⁩
Debug Info:

    
    Anki 2.1.61 (0c1eaf4c) Python 3.10.10 Qt 6.5.0 PyQt 6.5.0
    Platform: Linux-6.1.26-1-MANJARO-x86_64-with-glibc2.37
    Flags: frz=False ao=True sv=3
    Add-ons, last update check: 2023-04-29 15:04:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-27T02:28, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T21:24, 'None', '']
    AnkiConnect ['2055492159', 2023-04-11T19:20, 'None', '']
    Batch Editing ['291119185', 2019-06-02T20:47, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2022-10-09T14:05, 'None', '']
    Opening the same window multiple time ['354407385', 2020-05-16T02:59, 'None', '']
    Paste Images As WebP ['1151815987', 2023-04-29T14:42, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
    Review Hotmouse ['1928346827', 2022-05-17T06:25, '2.6', mod]
    ZIM Reader ['951350249', 2023-02-21T22:12, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1151815987 1556734708 1771074083 1928346827 2055492159 291119185 354407385 817108664 874215009 951350249
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

OS: 
![grafik](https://user-images.githubusercontent.com/121114125/235304118-4ee7c0fa-d420-41a8-a5c1-cab5df0a5316.png)

**Comment by tatsumoto-ren** [comment]
Thanks for reporting. Should be fixed now.
