### ISSUE TITLE
Drag & Drop to Edit Window while Reviewing changes focus from Edit window to Review window

### ISSUE THREAD

**Issue by kanjieater** [Ajatt-Tools/PasteImagesAsWebP#27]
Noticed some odd behavior, so I figured I'd request to get it changed to match how Anki works without the add-on in a consistent way.
Steps to reproduce:
1. Review Cards
2. Decide to add an image to a card & open the edit dialog
3. Drag an image to the Image field of the Edit dialog
4. The review window takes focus, a tooltip is shown, and the edit dialog box is still opened (and depending on where you opened the edit dialog, potentially covered by the review window which took focus)

The request would be to have the edit window stay in focus, and not do any focus switching to the review window when using drag & drop, just like when the add-on is not installed.

(PS: I'm going from 22GBs of images to 3GBs. Thank you for making this.)

**Comment by tatsumoto-ren** [comment]
I didn't notice any focus changes but this is probably because I use i3wm, which you should do too 😏

Maybe the focus shifts because the parent of the tooltip is set to `mw`. I guess it should be the current window instead.

**Comment by kanjieater** [comment]
That fixed it. Thank you for saving me so much disk space and making this easy to use!

**Comment by tatsumoto-ren** [comment]
Glad it helped!
