### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by galantra** [Ajatt-Tools/PasteImagesAsWebP#30]
Anki is capable of displaying .avif images now, a newer generation image format that's even better than webp.

**Comment by tatsumoto-ren** [comment]
Why do you think it's better?

**Comment by tatsumoto-ren** [comment]
This addon uses cwebp to convert images to webp. I don't know if such tool exists for avif but you can always rely on ffmpeg as it's the most versatile.

**Comment by tatsumoto-ren** [comment]
Yeah this is a viable solution. Some details:

* you replace webp with avif, but I think it would be better to provide both options at least for some transition period
* using ffmpeg instead of imagemagic would work better with the other planned features, e.g. converting audio files to opus.

**Comment by tatsumoto-ren** [comment]
I think the best option is to use cwebp (the old code path) to convert images to webp and ffmpeg for everything else. including ffmpeg with the add-on isn't necessary. People can install it separately if they want. But the add-on should show a warning when ffmpeg is not installed.
