### ISSUE TITLE
The latest version of the addon loads failly when start Anki

### ISSUE THREAD

**Issue by s609078902** [Ajatt-Tools/PasteImagesAsWebP#4]
My Anki version is 2.1.44

I will upload the picture when I go back home due to my company's policy.

**Comment by tatsumoto-ren** [comment]
That's very unexpected. I'm looking forward to more information on this.

**Comment by s609078902** [comment]
Hello, after uninstalling and reinstaling the addon, the problem was solved. So excited I can use the addon again.
