### ISSUE TITLE
Bulk-convert to wepb bug

### ISSUE THREAD

**Issue by aPaci95** [Ajatt-Tools/PasteImagesAsWebP#5]
Hello, firstly: your addon is great. It really is a life saver. That said, I tried to use the bulk-convert feature for a bunch of cards today and i find out that if multiple cards use the exact same image (let's say "tree.jpg"), when i bulk convert every single tree.jpg is converted in a different wepb file (tree1.webp; tree2.webp, etc.). I suppose this isn't intended, so i just wanted to report it just in case you wanted to fix it or to put a disclamer in the addon page... for example if some user (like me) used the same image for many cards, the number of pictures in the collection folder could potentially grow tenfold

**Comment by tatsumoto-ren** [comment]
It's not really a bug, it was unintentionally made this way. I think we should fix it, I'll work on it.

**Comment by aPaci95** [comment]
Thank you very much, I'm looking forward to it !!

**Comment by tatsumoto-ren** [comment]
Should work as expected now.

**Comment by tatsumoto-ren** [comment]
https://www.youtube.com/watch?v=6w0kWyGiHys

**Comment by aPaci95** [comment]
Thank you very much!
