### ISSUE TITLE
Bulk-convert to wepb crashes when it encounter missing media

### ISSUE THREAD

**Issue by aPaci95** [Ajatt-Tools/PasteImagesAsWebP#8]
As the title says, bulk-convert to wepb crashes when it encounter missing media. As there isn't any way to delete missing media from notes beside deleting them manually, would it be possible to add a feature to just skip missing media while bulk-converting?
Thank you very much, and have a nice day!

**Comment by tatsumoto-ren** [comment]
> As the title says, bulk-convert to wepb crashes when it encounter missing media.

This is very unfortunate. I'll try fixing it.
