### ISSUE TITLE
Bulk-convert to WebP crashing

### ISSUE THREAD

**Issue by woofingcough** [Ajatt-Tools/PasteImagesAsWebP#9]
Just want to let you know that every time I try to convert https://ankiweb.net/shared/info/969647708 this deck's images files into WebP format, the whole Anki crashes. Thanks for making this wonderful add-on, by the way.

**Comment by tatsumoto-ren** [comment]
Thanks for reporting. I'll try converting the linked deck to see why it crashes.

**Comment by tatsumoto-ren** [comment]
Does the issue persist after the recent update? If you still experience the crash, please provide a stack trace.

**Comment by woofingcough** [comment]
Nope. It has been resolved. Thanks heaps!
